repository:
  name: test
  description: change...4
  default_branch: master
  
labels:
  - name: bug
    color: CC0000
  - name: feature
    color: 336699
  - name: first-timers-only
  
branches:
  - name: master
    protection:
      required_pull_request_reviews:
         required_approving_review_count: 1
      enforce_admins: true

