repository:
  name: test
  description: change
  default_branch: master
  
labels:
  - name: bug
    color: CC0000
  - name: feature
    color: 336699
  - name: first-timers-only
  
branches:
  - name: 'master'
    protection:
      enforce_admins: true

