repository:
  name: test
  description: description of repo
  default_branch: master

branches:
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      enforce_admins: true
