repository:
  name: test
  description: change
  default_branch: test
  
labels:
  - name: bug
    color: CC0000
  - name: feature
    color: 336699
  - name: first-timers-only
  
branches:
  - name: test
    protection:
      enforce_admins: 
